# Generated by Django 3.0.4 on 2020-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200425_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='text',
            field=models.CharField(blank=True, default='noname', max_length=30),
        ),
    ]
