# Generated by Django 3.0.4 on 2020-04-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200425_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='describe',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
