# Generated by Django 3.0.4 on 2020-04-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_testmodel_describe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='text',
        ),
    ]
