# Generated by Django 3.0.4 on 2020-04-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200426_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_post',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='image',
            new_name='image_thread',
        ),
    ]
