# Generated by Django 3.0.4 on 2020-04-26 13:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200426_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=FutureWarning, quality=0, size=[400, 250], upload_to='media/'),
        ),
    ]
