# Generated by Django 3.0.4 on 2020-04-26 14:10

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200426_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=0, size=[400, 250], upload_to='media/'),
        ),
    ]
