# Generated by Django 3.0.4 on 2020-04-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200426_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
