# Generated by Django 3.0.4 on 2020-04-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200427_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.ManyToManyField(to='home.Post'),
        ),
    ]
