# Generated by Django 3.0.4 on 2020-04-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_post_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='home.Post'),
        ),
    ]
