# Generated by Django 3.0.4 on 2020-04-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200428_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.ManyToManyField(blank=True, default=None, to='home.Post'),
        ),
    ]
