# Generated by Django 3.0.4 on 2020-04-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20200428_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='home.Post', verbose_name='answer'),
        ),
    ]
